### ISSUE TITLE
a question about transformations

### ISSUE THREAD

**Issue by 6xfh** [MIC-DKFZ/batchgenerators#51] opened 2019-11-12 07:48 UTC
Hello,

I have this problem（    mirror_transform = MirrorTransform(axes=(2, 3))
  File "/home/xy/hb/MIC/batchgenerators-master/batchgenerators/transforms/spatial_transforms.py", line 199, in __init__
    raise ValueError("MirrorTransform now takes the axes as the spatial dimensions. What previously was "
ValueError: MirrorTransform now takes the axes as the spatial dimensions. What previously was axes=(2, 3, 4) to mirror along all spatial dimensions of a 5d tensor (b, c, x, y, z) is now axes=(0, 1, 2). Please adapt your scripts accordingly） when I reproduce your code（MIC-DKFZ/batchgenerators）. What's the reason? Looking forward to your reply!

                                                                                                                                                sincere

                                                                                                                                                  Bing

**Comment by FabianIsensee** [comment] 2019-11-12 09:11
Hi,
as the message says you need to change the channels. Use `mirror_transform = MirrorTransform(axes=(0, 1)`

Was this code taken from our repo? If so, from where? I will need to fix it if it was.
Kind regards,
Fabian

**Comment by FabianIsensee** [comment] 2019-11-12 09:13
Found and fixed it, sorry for the inconvenience!
Thanks for pointing out this issue!
Best,
Fabian

**Comment by 6xfh** [comment] 2019-11-12 09:19
hi，this code is from GitHub，thank you！------------------ 原始邮件 ------------------
发件人: "Fabian Isensee"<notifications@github.com>
发送时间: 2019年11月12日(星期二) 下午5:13
收件人: "MIC-DKFZ/batchgenerators"<batchgenerators@noreply.github.com>;
抄送: "6xfh"<1342814449@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [MIC-DKFZ/batchgenerators] a question about transformations (#51)



Found and fixed it, sorry for the inconvenience!
 Thanks for pointing out this issue!
 Best,
 Fabian
 
&mdash;

**Comment by 6xfh** [comment] 2019-11-12 12:24
Hello, is there any error in this code（from batchgenerators.transforms.spatial_transforms import Mirror     / mirror_transform = Mirror(axes=(0, 1))）? When I am running, I will prompt that I can't import, but I'll change it to this sentence（from batchgenerators.transforms.spatial_transforms import MirrorTransform/&nbsp; &nbsp;&nbsp;mirror_transform = MirrorTransform(axes=(0, 1))&nbsp;）
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Best,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Bing


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Fabian Isensee"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 下午5:13
收件人:&nbsp;"MIC-DKFZ/batchgenerators"<batchgenerators@noreply.github.com&gt;;
抄送:&nbsp;"黄冰"<1342814449@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MIC-DKFZ/batchgenerators] a question about transformations (#51)




Found and fixed it, sorry for the inconvenience!
 Thanks for pointing out this issue!
 Best,
 Fabian

**Comment by FabianIsensee** [comment] 2019-11-12 12:36
sorry. It is fixed now

**Comment by 6xfh** [comment] 2019-11-20 02:51
Hello, can this code output single channel picture? Where is the relevant code?


发自我的iPhone


------------------ Original ------------------

**Comment by FabianIsensee** [comment] 2019-11-22 09:29
Hi,
please be more specific. What is is you would like to do?

**Comment by 6xfh** [comment] 2019-11-22 12:09
Hello! First thank you for your reply, I want to use your code for medical image enhancement, the output is 8 bit depth of RGB medical image (format is GIF), but now I use your code output is 24 bit RGBA image (format is tif), so I would like to ask how to modify, thank you!




发自我的iPhone


------------------ Original ------------------

**Comment by FabianIsensee** [comment] 2019-11-22 15:50
I am really not sure what the problem is. 'data' is always a tensor of shape (b, c, x, y) or (b, c, x, y, z). b being the batch dimension and c being the number of color channels. batchgenerators does not care how many color channels you have

**Comment by 6xfh** [comment] 2019-11-25 02:06
Hello, then why is it that medical images with 8 bit depth are sent out with 24 or 32 bit medical images?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Fabian Isensee"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月22日(星期五) 晚上11:50
收件人:&nbsp;"MIC-DKFZ/batchgenerators"<batchgenerators@noreply.github.com&gt;;
抄送:&nbsp;"黄冰"<1342814449@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MIC-DKFZ/batchgenerators] a question about transformations (#51)




I am really not sure what the problem is. 'data' is always a tensor of shape (b, c, x, y) or (b, c, x, y, z). b being the batch dimension and c being the number of color channels. batchgenerators does not care how many color channels you have

**Comment by FabianIsensee** [comment] 2019-11-25 08:15
Hi,
most deep learning frameworks operate on float32. It makes sense to do the casting in the background workers so that the main thread can concentrate on the training.
Best,
Fabian

**Comment by 6xfh** [comment] 2019-11-26 14:19
Hi，
&nbsp; &nbsp; &nbsp;&nbsp;I already know how to modify it, thank you!
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Sincerely,
&nbsp;Bing
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;



发自我的iPhone


------------------ Original ------------------

**Closed** 2019-12-30 08:54 UTC
